<?php

/**
 * Implementation of hook_uuid_features_default_terms().
 */
function fserver_categories_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'uuid' => '8a163168-8a58-11e1-ba49-0022680ba85d',
    'name' => 'Administration',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '8a161a20-8a58-11e1-ba49-0022680ba85d',
  );
  $terms[] = array(
    'uuid' => '8a163ab4-8a58-11e1-ba49-0022680ba85d',
    'name' => 'Commerce/Advertising',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '8a161a20-8a58-11e1-ba49-0022680ba85d',
  );
  $terms[] = array(
    'uuid' => '8a1641b2-8a58-11e1-ba49-0022680ba85d',
    'name' => 'Community',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '8a161a20-8a58-11e1-ba49-0022680ba85d',
  );
  $terms[] = array(
    'uuid' => '8a164874-8a58-11e1-ba49-0022680ba85d',
    'name' => 'Content',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '8a161a20-8a58-11e1-ba49-0022680ba85d',
  );
  $terms[] = array(
    'uuid' => '8a164f36-8a58-11e1-ba49-0022680ba85d',
    'name' => 'Content Access Control',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '8a161a20-8a58-11e1-ba49-0022680ba85d',
  );
  $terms[] = array(
    'uuid' => '8a1655ee-8a58-11e1-ba49-0022680ba85d',
    'name' => 'Content Construction Kit (CCK)',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '8a161a20-8a58-11e1-ba49-0022680ba85d',
  );
  $terms[] = array(
    'uuid' => '8a165ca6-8a58-11e1-ba49-0022680ba85d',
    'name' => 'Content Display',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '8a161a20-8a58-11e1-ba49-0022680ba85d',
  );
  $terms[] = array(
    'uuid' => '8a16635e-8a58-11e1-ba49-0022680ba85d',
    'name' => 'Database Drivers',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '8a161a20-8a58-11e1-ba49-0022680ba85d',
  );
  $terms[] = array(
    'uuid' => '8a166a2a-8a58-11e1-ba49-0022680ba85d',
    'name' => 'Developer',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '8a161a20-8a58-11e1-ba49-0022680ba85d',
  );
  $terms[] = array(
    'uuid' => '8a1670d8-8a58-11e1-ba49-0022680ba85d',
    'name' => 'Drush',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '8a161a20-8a58-11e1-ba49-0022680ba85d',
  );
  $terms[] = array(
    'uuid' => '8a167880-8a58-11e1-ba49-0022680ba85d',
    'name' => 'E-commerce',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '8a161a20-8a58-11e1-ba49-0022680ba85d',
  );
  $terms[] = array(
    'uuid' => '8a167fba-8a58-11e1-ba49-0022680ba85d',
    'name' => 'Evaluation/Rating',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '8a161a20-8a58-11e1-ba49-0022680ba85d',
  );
  $terms[] = array(
    'uuid' => '8a1686b8-8a58-11e1-ba49-0022680ba85d',
    'name' => 'Event',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '8a161a20-8a58-11e1-ba49-0022680ba85d',
  );
  $terms[] = array(
    'uuid' => '8a168dac-8a58-11e1-ba49-0022680ba85d',
    'name' => 'Examples',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '8a161a20-8a58-11e1-ba49-0022680ba85d',
  );
  $terms[] = array(
    'uuid' => '8a16948c-8a58-11e1-ba49-0022680ba85d',
    'name' => 'Features Package',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '8a161a20-8a58-11e1-ba49-0022680ba85d',
  );
  $terms[] = array(
    'uuid' => '8a169b80-8a58-11e1-ba49-0022680ba85d',
    'name' => 'Fields',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '8a161a20-8a58-11e1-ba49-0022680ba85d',
  );
  $terms[] = array(
    'uuid' => '8a16a260-8a58-11e1-ba49-0022680ba85d',
    'name' => 'File Management',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '8a161a20-8a58-11e1-ba49-0022680ba85d',
  );
  $terms[] = array(
    'uuid' => '8a16b958-8a58-11e1-ba49-0022680ba85d',
    'name' => 'Filters/Editors',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '8a161a20-8a58-11e1-ba49-0022680ba85d',
  );
  $terms[] = array(
    'uuid' => '8a16c04c-8a58-11e1-ba49-0022680ba85d',
    'name' => 'Games and Amusements',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '8a161a20-8a58-11e1-ba49-0022680ba85d',
  );
  $terms[] = array(
    'uuid' => '8a16c740-8a58-11e1-ba49-0022680ba85d',
    'name' => 'Import/Export',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '8a161a20-8a58-11e1-ba49-0022680ba85d',
  );
  $terms[] = array(
    'uuid' => '8a16ce34-8a58-11e1-ba49-0022680ba85d',
    'name' => 'JavaScript Utilities',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '8a161a20-8a58-11e1-ba49-0022680ba85d',
  );
  $terms[] = array(
    'uuid' => '8a16d58c-8a58-11e1-ba49-0022680ba85d',
    'name' => 'Location',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '8a161a20-8a58-11e1-ba49-0022680ba85d',
  );
  $terms[] = array(
    'uuid' => '8a16dc62-8a58-11e1-ba49-0022680ba85d',
    'name' => 'Mail',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '8a161a20-8a58-11e1-ba49-0022680ba85d',
  );
  $terms[] = array(
    'uuid' => '8a16e342-8a58-11e1-ba49-0022680ba85d',
    'name' => 'Media',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '8a161a20-8a58-11e1-ba49-0022680ba85d',
  );
  $terms[] = array(
    'uuid' => '8a16ea18-8a58-11e1-ba49-0022680ba85d',
    'name' => 'Mobile',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '8a161a20-8a58-11e1-ba49-0022680ba85d',
  );
  $terms[] = array(
    'uuid' => '8a170f34-8a58-11e1-ba49-0022680ba85d',
    'name' => 'Multilingual',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '8a161a20-8a58-11e1-ba49-0022680ba85d',
  );
  $terms[] = array(
    'uuid' => '8a17165a-8a58-11e1-ba49-0022680ba85d',
    'name' => 'Multisite',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '8a161a20-8a58-11e1-ba49-0022680ba85d',
  );
  $terms[] = array(
    'uuid' => '8a171ed4-8a58-11e1-ba49-0022680ba85d',
    'name' => 'Novelty',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '8a161a20-8a58-11e1-ba49-0022680ba85d',
  );
  $terms[] = array(
    'uuid' => '8a1725fa-8a58-11e1-ba49-0022680ba85d',
    'name' => 'Organic Groups (OG)',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '8a161a20-8a58-11e1-ba49-0022680ba85d',
  );
  $terms[] = array(
    'uuid' => '8a172cd0-8a58-11e1-ba49-0022680ba85d',
    'name' => 'Paging',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '8a161a20-8a58-11e1-ba49-0022680ba85d',
  );
  $terms[] = array(
    'uuid' => '8a1733a6-8a58-11e1-ba49-0022680ba85d',
    'name' => 'Path Management',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '8a161a20-8a58-11e1-ba49-0022680ba85d',
  );
  $terms[] = array(
    'uuid' => '8a173a72-8a58-11e1-ba49-0022680ba85d',
    'name' => 'Performance and Scalability',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '8a161a20-8a58-11e1-ba49-0022680ba85d',
  );
  $terms[] = array(
    'uuid' => '8a174206-8a58-11e1-ba49-0022680ba85d',
    'name' => 'Project management',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '8a161a20-8a58-11e1-ba49-0022680ba85d',
  );
  $terms[] = array(
    'uuid' => '8a17490e-8a58-11e1-ba49-0022680ba85d',
    'name' => 'RDF',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '8a161a20-8a58-11e1-ba49-0022680ba85d',
  );
  $terms[] = array(
    'uuid' => '8a175002-8a58-11e1-ba49-0022680ba85d',
    'name' => 'Rules',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '8a161a20-8a58-11e1-ba49-0022680ba85d',
  );
  $terms[] = array(
    'uuid' => '8a1756ec-8a58-11e1-ba49-0022680ba85d',
    'name' => 'Search',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '8a161a20-8a58-11e1-ba49-0022680ba85d',
  );
  $terms[] = array(
    'uuid' => '8a175dcc-8a58-11e1-ba49-0022680ba85d',
    'name' => 'Security',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '8a161a20-8a58-11e1-ba49-0022680ba85d',
  );
  $terms[] = array(
    'uuid' => '8a1764b6-8a58-11e1-ba49-0022680ba85d',
    'name' => 'Site Navigation',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '8a161a20-8a58-11e1-ba49-0022680ba85d',
  );
  $terms[] = array(
    'uuid' => '8a176c86-8a58-11e1-ba49-0022680ba85d',
    'name' => 'Statistics',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '8a161a20-8a58-11e1-ba49-0022680ba85d',
  );
  $terms[] = array(
    'uuid' => '8a177398-8a58-11e1-ba49-0022680ba85d',
    'name' => 'Spam Prevention',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '8a161a20-8a58-11e1-ba49-0022680ba85d',
  );
  $terms[] = array(
    'uuid' => '8a177aaa-8a58-11e1-ba49-0022680ba85d',
    'name' => 'Syndication',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '8a161a20-8a58-11e1-ba49-0022680ba85d',
  );
  $terms[] = array(
    'uuid' => '8a1781a8-8a58-11e1-ba49-0022680ba85d',
    'name' => 'Taxonomy',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '8a161a20-8a58-11e1-ba49-0022680ba85d',
  );
  $terms[] = array(
    'uuid' => '8a17889c-8a58-11e1-ba49-0022680ba85d',
    'name' => 'Theme Enhancements',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '8a161a20-8a58-11e1-ba49-0022680ba85d',
  );
  $terms[] = array(
    'uuid' => '8a178fa4-8a58-11e1-ba49-0022680ba85d',
    'name' => 'Third-party Integration',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '8a161a20-8a58-11e1-ba49-0022680ba85d',
  );
  $terms[] = array(
    'uuid' => '8a1796f2-8a58-11e1-ba49-0022680ba85d',
    'name' => 'User Access &amp; Authentication',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '8a161a20-8a58-11e1-ba49-0022680ba85d',
  );
  $terms[] = array(
    'uuid' => '8a179e0e-8a58-11e1-ba49-0022680ba85d',
    'name' => 'User Management',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '8a161a20-8a58-11e1-ba49-0022680ba85d',
  );
  $terms[] = array(
    'uuid' => '8a17a520-8a58-11e1-ba49-0022680ba85d',
    'name' => 'Utility',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '8a161a20-8a58-11e1-ba49-0022680ba85d',
  );
  $terms[] = array(
    'uuid' => '8a17ac14-8a58-11e1-ba49-0022680ba85d',
    'name' => 'Views',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '8a161a20-8a58-11e1-ba49-0022680ba85d',
  );
  return $terms;
}
